### ISSUE TITLE
Post copy of slides

### ISSUE THREAD

**Issue by SmithSamuelM** [cachedout/susecon#1]
Could you post a copy of your slides from the presentation.

**Comment by cachedout** [comment]
Done. Thanks, @SmithSamuelM !

**Comment by SmithSamuelM** [comment]
Thanks. Good to see you again if only remotely.  Sounds like doing some cool stuff.

**Comment by cachedout** [comment]
You as well. Heard you've been working on you've been working on cool stuff too. Glad to hear it!
